import "@radix-ui/themes/styles.css";
// import "@radix-ui/themes";
import "./globals.css";
import "./theme-config.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <main className="p-5">
          <AuthProvider>
            <Theme appearance="light" accentColor="violet" radius="small">
              <Navbar />
              <Container>{children}</Container>
              {/* <ThemePanel /> */}
            </Theme>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
